# Numpy: $n$-dimenziós adattömbök 

##     Adattömbök létrehozása


A **numpy** csomag importálása:

In [52]:
import numpy as np

**$n$-dimenziós adattömb** létrehozása:

In [53]:
A = np.array([[2, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(A)

[[ 2  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Üres adattömb** létrehozása (a memória inicializálása nélkül):

In [54]:
B = np.empty((2, 2))
print(B)

[[1.8 3.6]
 [5.4 7.2]]


**Nullmátrix** létrehozása:

In [55]:
C = np.zeros((2, 3))
print(C)

[[0. 0. 0.]
 [0. 0. 0.]]


**1-eseket tartalmazó mátrix** létrehozása:

In [56]:
D = np.ones((3, 2))
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


A fenti adatok *float64* típusúak. Ha integer típusú adatokkal szeretnénk feltölteni, akkor *dtype* paramétert is meg kell adnunk:

In [57]:
D = np.ones((3, 2), dtype=int)
print(D)

[[1 1]
 [1 1]
 [1 1]]


**Egységmátrix** lérehozása:

In [58]:
E = np.eye(3, dtype=int)
print(E)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Konstans értékekkel feltöltött mátrix** létrehozása:

In [59]:
F = np.full((2,3), 7)
print(F)

[[7 7 7]
 [7 7 7]]


<br>
**Adott lépésközzel** generált számokból álló mátrixot szintén könnyedén inicializálhatunk.  
Példaként hozzunk létre a [10,22) értéktartományból 2-es lépésközzel generált számokból egy 2$*$3-as adatmátrixot! Első lépésként hozzuk létre a számokat tartalmazó listát, majd a *resize* metódussal változtassuk meg a tömb méretét.

In [60]:
G = np.arange(10, 22, 2)
G.resize((2, 3))
print(G)

[[10 12 14]
 [16 18 20]]


**Egyenletes lépésközzel** generált számokból álló mátrix létrehozása.  
Példaként hozzunk létre a [0,10] értéktartományból generálva egy 1$*$5-ös tömböt oly módon, hogy az 5 szám egyenletesen legyen elosztva az értéktartományon belül!

In [61]:
H = np.linspace(0, 10, 5, endpoint=True, dtype=int)
print(H)

[ 0  2  5  7 10]


Ha a [0, 10) tartományban szeretnénk elosztani az 5 számot, akkor ezt a következőképpen tudjuk megtenni: 

In [62]:
H = np.linspace(0, 9, 5, endpoint=False)
print(H)

[0.  1.8 3.6 5.4 7.2]


<br>
**Random számokból** álló adattömb létrehozására számos lehetőség létezik.  
Ehhez érdemes áttekinteni a következő leírást: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html.  

Csupán néhány példa:  
2$*$3-as adattömb [0, 1) intervallumból egyenletes eloszlással:

In [63]:
I = np.random.rand(2, 3)
print(I)

[[0.98558263 0.09512728 0.86233368]
 [0.4645078  0.63784864 0.3764799 ]]


2∗3-as adattömb [0, 1) intervallumból normál eloszlással:

In [64]:
I = np.random.randn(2, 3)
print(I)

[[-0.18499793  1.88486152 -0.12300287]
 [ 0.10043599 -2.0220047  -0.42081233]]


[100, 200) intervallumból generált 10 db egész szám egyenletes eloszlással:

In [65]:
J = np.random.randint(100, 200, 10)
print(J)

[149 131 158 123 148 171 116 135 113 116]


[10, 20) intervallumból generált 5 db véletlen szám egyenletes eloszlással:

In [66]:
K = np.random.uniform(10, 20, 5)
print(K)

[18.12121094 10.69200238 16.64727801 14.67144873 15.7132639 ]


[10, 20) intervallumból generált 2*3-as adattömb random, egyenletes eloszlással:

In [67]:
L = np.random.uniform(10, 20, (2, 3))
print(L)

[[18.97051106 14.82830209 10.97616137]
 [18.75541208 18.86379138 15.84849302]]


<br>

## Tömbök építése

Hozzunk létre 2 adattömböt, majd "másoljuk" egymás mellé őket a lehetséges 2 módon!

In [68]:
T1 = np.array([[1, 2, 3], [4, 5, 6]])
print(T1)

[[1 2 3]
 [4 5 6]]


In [69]:
T2 = np.array([[7, 8, 9], [10, 11, 12]])
print(T2)

[[ 7  8  9]
 [10 11 12]]


T1 és T2 **tömbök halmozása vertikálisan**:

In [70]:
np.concatenate((T1, T2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
np.vstack((T1, T2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

T1 és T2 **tömbök halmozása horizontálisan**:

In [72]:
np.concatenate((T1, T2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [73]:
np.hstack((T1, T2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

<br>

## Tömbök mérete és típusa

Gyakran van szükségünk arra, hogy lekérdezzük meglévő adattömbjeink méretét, és a bennük található adatok típusát. Ezt a következőkéépen tudjuk megtenni: 

**Tömb dimenzióinak száma**:

In [74]:
T1.ndim

2

**Tömb méretének** lekérdezése:

In [75]:
T1.shape

(2, 3)

**Tömb elemeinek száma**:

In [76]:
T1.size

6

**Tömb 'hossza'** (benne lévő listák száma):

In [77]:
len(T1)

2

<br>
Tömbben lévő **elemek típusa**:

In [78]:
T1.dtype.name

'int64'

Tömb elemeinek **típuskonverziója**:

In [79]:
print(T1)
T1.dtype.name

[[1 2 3]
 [4 5 6]]


'int64'

In [80]:
M = T1.astype(int)
print(M)
M.dtype.name

[[1 2 3]
 [4 5 6]]


'int64'

<br>


## Tömbök elemei és résztömbök (slice and dice)

Tömb elemeinek elérésekor ügyelnünk kell arra, hogy:
- a sor- és oszlopindexek 0-tól kezdődnek! 
- tartományok megadása esetén alulról zárt, felülről nyitott tartományokat tudunk megadni!

Hivatkozások:
- [sor, oszlop]  
- : minden sor/oszlop
- :n az első $n$ sor/oszlop
- :-n kivéve az utolsó $n$ sor/oszlop
- ::n minden $n$-edik sor/oszlop
- ::-1 sorok/oszlopok inverze



In [81]:
print(A)

[[ 2  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [82]:
print(A[1, 3])

8


In [83]:
print(A[:, 2])

[ 3  7 11 15]


In [84]:
print(A[3, :])

[13 14 15 16]


In [85]:
print(A[1:3, 1])

[ 6 10]


In [86]:
print(A[:, [0, 2]])

[[ 2  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [87]:
print(A[:, :2])

[[ 2  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [88]:
print(A[:, :-1])

[[ 2  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [89]:
print(A[::2, ::2])

[[ 2  3]
 [ 9 11]]


In [90]:
print(A[:, ::-1])

[[ 4  3  2  2]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


<br>


## Keresés a tömbökben

In [91]:
x = np.array([[5, 9, 2], [3, 0, 4]])
print(x)

[[5 9 2]
 [3 0 4]]


Az adattömbök elemei között legegyszerűbben logikai feltételek megadásával kereshetünk. Eredményképpen azokat az elemeket kapjuk vissza, melyek kielégítik a logikai feltételt.  
<br>
Például melyek az *x* tömb azon elemei, amelyek értéke kisebb, mint 5?

In [92]:
x[x < 5]

array([2, 3, 0, 4])

Melyek az *x* tömb páros elemei?

In [93]:
x[x % 2 == 0]

array([2, 0, 4])

<br>
Ha azt szeretnénk megtudni, hogy mik azon elemek **indexei**, amelyek eleget tesznek a feltételnek, akkor az **np.argwhere** függvényt kell alkalmaznunk. (Használható még az **np.where** is.)

In [94]:
np.argwhere(x < 5)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [95]:
np.where(x < 5)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

Gyakran van szükségünk a **nem 0 elemek keresésére** is, melyet így is meg tudunk tenni:

In [96]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 2]])

<br>

## Hivatkozás és másolás

Nem mindegy, hogy egy adattömbre hivatkozunk-e egy másik névvel, vagy másolatot hozunk-e létre belőle. Előbbi esetben referenciaként jön létre az adatmátrix, míg a második esetben az eredeti adattömb másolata készül el.  
<br>
Nézzünk rá egy rövid példát!

In [97]:
x = np.array([[5, 9, 2], [3, 0, 4]])
y = x  # reference
z = np.copy(x)  # copy
x

array([[5, 9, 2],
       [3, 0, 4]])

In [98]:
x[0, 0] = 999

In [99]:
print(x)

[[999   9   2]
 [  3   0   4]]


In [100]:
print(y)

[[999   9   2]
 [  3   0   4]]


In [101]:
print(z)

[[5 9 2]
 [3 0 4]]


<br>

## Egyéb

**Tömbök transzponálása**:

In [102]:
np.transpose(A)

array([[ 2,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])